### ISSUE TITLE
Document use of cloud object storage

### ISSUE THREAD

**Issue by jnywong** [2i2c-org/docs#226]
_Follows on from #215_

### Related material

- https://github.com/2i2c-org/infrastructure/issues/3665
- https://github.com/2i2c-org/docs/issues/179)
- https://github.com/2i2c-org/infrastructure/issues/4281

```[tasklist]
### Tasks
- [x] Review NASA Openscapes Python example https://github.com/NASA-Openscapes/earthdata-cloud-cookbook/pull/325
- [ ] https://github.com/2i2c-org/infrastructure/issues/4214
- [ ] https://github.com/2i2c-org/infrastructure/issues/4216
- [x] Reference [NASA Openscapes examples](https://nasa-openscapes.github.io/earthdata-cloud-cookbook/how-tos/using-s3-storage.html) in the Service Guide once it's merged
```

**Comment by jnywong** [comment]
🙀

**Comment by yuvipanda** [comment]
And just to clarify, this only accounts for *download* - upload is free. Download pricing depends on where they're downloading it to. The cloud billing topic doc linked has more information.

**Comment by jnywong** [comment]
Haha got it yes, ingress vs egress 💰 I'm going to include _all_ of the warning callouts
