### ISSUE TITLE
Plan for Berkeley education team syncs

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/docs#38]
## Background

As the hub begin running in S21, we should plan how to synchronize our activity so that we can stay on the same page and coordinate action items.

## ToDo

- [ ] Agree upon an initial team sync
- [ ] Agree upon the format for team syncs
- [ ] Define a schedule for team syncs

**Comment by sandeepsainath** [comment]
As of our last meeting (12/18/20), we targeted a date of Jan 18th-19th for an initial DSUS/2i2c post-winter sync with roughly bi-weekly meetings after. Does this schedule still work?

The format could be an hour-long meeting to:
(1) provide important updates from both DSUS and 2i2c, and
(2) address major concerns and/or strategic questions that are either recent or were not fully addressed by other forms of communication (Slack/email/Discourse).

(1) could probably take around 10 minutes, with the rest of the time devoted to (2).

**Comment by choldgraf** [comment]
Yep that sounds good to me. And I am always a fan of putting agendas on meetings ahead of time, if at all possible. Main questions/topics I have right now are:

1. What's the status of expected new hubs for S21?
2. Agreeing on a plan for #36 
  - Specifically I think we should decide whether I should purchase a Discourse plan for 2i2c with my credit card haha
3. Discussing who will serve in the role that James P. was serving in previously (in the meantime before another person is hired).
4. Discuss any important dates that we need to have in mind (e.g., if institutions have given us any specific dates for class start etc)
5. Update from us on our hiring plans

**Comment by choldgraf** [comment]
I'm closing this one as I think it's gone out-of-date - we've been running these educational hubs for a while now and haven't had a strong need for regular team syncs
